<h1><center>  lab 3 : ML Overview: Supervised Learning algorithms </center>
    
<img src="https://i.pinimg.com/736x/02/66/bd/0266bd22348df67f4cf04ab83bf38e5a.jpg" width="600">


```Created by Jinnie Shin (jinnie.shin@coe.ufl.edu)```\
```Date: May 19th 2022```

```Image source: https://i.pinimg.com/736x/02/66/bd/0266bd22348df67f4cf04ab83bf38e5a.jpg```

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmNf86oJnfhpkPA9LnrFnAbfwF2VywPYpB_w&usqp=CAU" align="left" width="70" height="70" align="left"> 

 ### Required Packages or Dependencies
 We learned how to download packages in python in our last lecture -- e.g., pip install `numpy`

In [4]:
#!pip install { } ! in case you run into the `package not avaialble` error
import pandas as pd 
import numpy as np 
#import matplotlib.pyplot as plt ### ----- pip install matplotlib

## Data

The data consisted of the labeled chats from an online collaborative problem-solving study (Hao et al., 2015). Each turn of the chats has been coded into **one of the four categories** of collaborative problem-solving skills (Link: https://repository.isls.org/bitstream/1/462/1/297.pdf)
- *Macro level evience* - infer: Collaborative problem-solving skills

#### Goal
- To create an automated classifier using machine learning methods to label the chats automatically



In [19]:
real_X=pd.read_csv('./week3_data/chat_bigram_feature.csv.gz',compression='gzip').values
real_y=pd.read_csv('./week3_data/chat_label.csv').values.ravel()

In [24]:
real_X


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

- Each turn of the chats is already converted into a numerical vector using a NLP vectorization approach (we will cover this in our NLP class :)) 
- So now one variable (or feature in CP) represents a uni-gram or a bi-gram token (e.g., "I", "I-HAVE")

In [65]:
real_y # Let's take a look at the output data together 

array([4, 4, 4, ..., 3, 3, 4])

- Like we explained earlier, the output variable is the hand-coded categorization of one of the four collaborative problem-solving skills

## 1. Regression OR Classification Problems?

> Our task is to predict the `output categories --y`  using the given set of features `X`. 

### Problem setting 1
> Let's assume that the complexity of the skill dimension is the **lowest in category 1** and the **highest in category 4**

$\rightarrow$ Predict whether the chat can be used to automatically predict the complexity of the problem solving skills

> We will implement and use a linear regression model, as our main prediction. We will take a look at how the model weights are learned using **the gradient descent algorithms**. 

### 1.1 Gradient Descent 
<img src="https://miro.medium.com/proxy/1*fBxEzbzP1KkqR7PTexJZdw.png" width="250">

> The objective of the learning algorithm is to determine the best possible values for the parameters (`w` and `b`), such that the overall loss (squared error loss) of the model is minimized as much as possible. \
> Let's solve this regression problem: `y = 4.0+(3.0𝑥0)+(1.0𝑥1)+(3.0𝑥2)+(0.5𝑥3)+(1.5𝑥4)`

In [31]:
num_samples = 200

x0 = 3.0 + np.random.standard_normal(num_samples)
x1 = 1.0 + np.random.standard_normal(num_samples)
x2 = -8.0 + np.random.standard_normal(num_samples)
x3 = -2.0 + np.random.standard_normal(num_samples)
x4 = 0.5 + np.random.standard_normal(num_samples)
y = 4.0 + 3.0 * x0 + 1.0 * x1 + 3.0 * x2 + 0.5 * x3 + 1.5 * x4 + np.random.standard_normal(num_samples)

X = np.column_stack((x0, x1, x2, x3, x4))
Y = y 

#### 1.1.1 Batch Gradient Descent (BGD)
source: https://www.youtube.com/watch?v=b4Vyma9wPHo 
<img src="https://i.ytimg.com/vi/b4Vyma9wPHo/maxresdefault.jpg" width='500'>


> Partial derivates of `b` and `w` in linear regression with the squared loss is: 
<img src="https://eli.thegreenplace.net/images/math/aef02f077919896478d0456619f934dcc5809142.png" width="250">

In [30]:
len(y)

200

In [32]:
def BGD(X, Y, b, w, alpha=0.005): # alpha is a learning rate, we will set it as 0.005 for now
   
    num_feat = X.shape[1]
    
    num_sample = X.shape[0] # This indicates the total number of data points (rows)

    b_grad = 0 #Intercept 
    
    w_grad = np.zeros(num_feat) # weight vector 
    
    for i in range(num_sample): # BGD first calculates the `b_grad` or `w_grad` 
                                # from the total sample N
        y = Y[i] # one sample, y
        x = X[i] # one sample, x 
        b_grad += -(2./float(num_sample)) * (y - (b + w.dot(x)))

        for j in range(num_feat):
            x_ij = x[j]
            w_grad[j] += -(2./float(num_sample)) * x_ij * (y - (b + w.dot(x)))

    b_new = b - alpha * b_grad
    w_new = np.array([w[i] - alpha * w_grad[i] for i in range(num_feat)])
    return b_new, w_new

In [34]:
def BGD_train(X, Y, alpha=0.005):
    b = 0
    w = np.zeros(X.shape[1])
    print('===== Start Training ====')
    for i in range(100000):
        b_new, w_new = BGD(X, Y, b, w, alpha=alpha)
        b = b_new
        w = w_new
        if i % 5000 == 0:
            print('{}: b = {}, w = {}'.format(i, np.round(b_new, 2), np.round(w_new, 2)))

    print('final: b = {}, w = {}'.format(np.round(b, 2), np.round(w, 2)))
    return b, w

> *Let's explore!*

In [35]:
BGD_train(X, Y)

===== Start Training ====
0: b = -0.1, w = [-0.28 -0.09  0.83  0.22 -0.04]
5000: b = 1.7, w = [2.94 0.93 2.69 0.48 1.61]
10000: b = 2.84, w = [2.91 0.91 2.8  0.51 1.61]
15000: b = 3.54, w = [2.89 0.9  2.87 0.53 1.6 ]
20000: b = 3.97, w = [2.87 0.9  2.92 0.55 1.6 ]
25000: b = 4.23, w = [2.87 0.9  2.94 0.55 1.6 ]
30000: b = 4.39, w = [2.86 0.89 2.96 0.56 1.6 ]
35000: b = 4.49, w = [2.86 0.89 2.97 0.56 1.59]
40000: b = 4.55, w = [2.86 0.89 2.98 0.56 1.59]
45000: b = 4.59, w = [2.85 0.89 2.98 0.56 1.59]
50000: b = 4.61, w = [2.85 0.89 2.98 0.56 1.59]
55000: b = 4.62, w = [2.85 0.89 2.98 0.56 1.59]
60000: b = 4.63, w = [2.85 0.89 2.98 0.56 1.59]
65000: b = 4.64, w = [2.85 0.89 2.99 0.56 1.59]
70000: b = 4.64, w = [2.85 0.89 2.99 0.56 1.59]
75000: b = 4.64, w = [2.85 0.89 2.99 0.57 1.59]
80000: b = 4.64, w = [2.85 0.89 2.99 0.57 1.59]
85000: b = 4.64, w = [2.85 0.89 2.99 0.57 1.59]


KeyboardInterrupt: 

<img src="https://i.pinimg.com/736x/2e/aa/7d/2eaa7d5021ca7c3c98bc93b98b9646fe.jpg" align="left" width="70" height="70" align="left">

 ## Task 1: Training & Testing data
>  **Q1.** In order to analyze large dataset efficiently, we will use the package `scikit-learn` to implement regression models. 
>> **Step 1**: Download the package `!pip install sklearn` \
>> **Step 2**: Import models ` from sklearn.linear_model import LinearRegression`\
>> **Step 3**: Call the module `lr = LinearRegression()` \
>> **Step 4**: Fit the dataset using `lr.fit({input}, {output})` and check the intercept and the coefficients using `lr.intercept_` and `lr.coef_`

> More information about the package is available at: https://scikit-learn.org/stable/modules/linear_model.html#ordinary-least-squares

> **Q2.** Compare the results with our findings. 

In [38]:
################################### YOUR CODE HERE #############################

from sklearn.linear_model import LinearRegression, LogisticRegression

lr = LinearRegression() # model development 

lr.fit(X, y) #model learning 

y_hat = lr.predict(X)

print('This is the intercept value of my linear regression -------')
print(lr.intercept_)
print('This is the coefficient value of my linear regression -------')
print(lr.coef_)


###############################################################################

This is the intercept value of my linear regression -------
4.6452278156334135
This is the coefficient value of my linear regression -------
[2.85291625 0.89002873 2.98601052 0.56510493 1.59376851]


<img src="https://i.pinimg.com/736x/2e/aa/7d/2eaa7d5021ca7c3c98bc93b98b9646fe.jpg" align="left" width="70" height="70" align="left">

 ## Task 2: Training & Testing data - using our real data
>  Q3. Let's try to use our `real_X` and `real_y` to investigate whether the chat can sufficiently predict the complexity of the CPS skills. In order to analyze large dataset efficiently, we will use the package `scikit-learn` to implement regression models. 
>
>> **Step 1**: Import models ` from sklearn.linear_model import LinearRegression`\
>> **Step 2**: Call a new module `lr = LinearRegression()` \
>> **Step 3**: Fit the dataset using `lr.fit({input}, {output})` and check the intercept and the coefficients using `lr.intercept_` and `lr.coef_`\
>> **Step 4**: Using the model you fit in Step 3, let's predict the outcome and round it up using `pred = lr.predict(real_X)`\
>> **Step 5**: Let's evaluate the prediction accuracy. First import `from sklearn.metrics import accuracy_score, r2_score`
and going back to your script `r2_score(pred, {output})` `accuracy_score(pred, {output})`

> More information about the package is available at: https://scikit-learn.org/stable/modules/linear_model.html#ordinary-least-squares

> Q4. Any problems with this evaluation scheme?

In [39]:
################################### YOUR CODE HERE #############################

from sklearn.linear_model import LinearRegression
lr = LinearRegression()  # step2: model development 
lr.fit(real_X, real_y)   # step3: model learning - fitting 

pred = lr.predict(real_X) # prediction 

from sklearn.metrics import accuracy_score, r2_score 

r2_score(pred, real_y) # step4: model evaluation 







###############################################################################

0.6402474636318217

<img src="https://scikit-learn.org/stable/_images/grid_search_cross_validation.png" width="600">

### Problem setting 2
> Let's classify the lables using the chat 

$\rightarrow$ classify the lables using the chat. 

> We will implement and use the support vector classifer and neural networks model (what we covered in the previous lecture :)) ), as our main prediction. We will take a look at how the model weights are learned using **the gradient descent algorithms**. 

### We will first define a few models we learned so far... 

In [40]:
from sklearn.svm import LinearSVC # for Support Vector Machine
model_SVM = LinearSVC()

from sklearn.neural_network import MLPClassifier #neural network 
nn = MLPClassifier()
# let's take a look: https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html

from sklearn.linear_model import LogisticRegression #logistic regression
lr = LogisticRegression()

> *Let's explore!*

In [43]:
from sklearn.svm import LinearSVC # for Support Vector Machine
from sklearn.metrics import accuracy_score # metric
from sklearn.model_selection import KFold  # evaluation scheme

kf = KFold(n_splits=5)

i=0
for train_index, test_index  in kf.split(real_X):
    
    X_train, X_test = real_X[train_index], real_X[test_index] #this is to find and define train-test-folds
    y_train, y_test = real_y[train_index], real_y[test_index]

    model_SVM = LinearSVC() #this is to define or develop a model 
    model_SVM.fit(X_train, y_train) #step 3 : model learning but only using the training set 
    pred = model_SVM.predict(X_test)
    print('iteration---', i+1)
    print(accuracy_score(pred, y_test))
    i+=1 
    


iteration--- 1
0.7215474583895637
iteration--- 2
0.6842105263157895
iteration--- 3
0.7125506072874493
iteration--- 4
0.7151215121512151
iteration--- 5
0.666966696669667
